setup_file: /workspace/veros/veros/setups/global_flexible/global_flexible.py

# Empty launcher so python script executes the template directly per srun task
launcher: ""
rank_env: SLURM_PROCID
local_rank_env: SLURM_LOCALID

memory_sample_interval: 5
communication_profile: true
jax_trace: true
profiler: none
profiler_args: ""
timesteps: 100
dt: 450
repetitions: 1

container_image: /lustre/fsn1/singularity/images/uyl42ho/jax-veros2.sif

environment:
  init: |
    module purge
    module load singularity

    export VEROS_ASSET_DIR=/lustre/fswork/projects/rech/yah/uyl42ho/veros_assets

strong:
  size: [720, 420, 80]

weak:
  local_size: [360, 160, 60]

topologies:
  - nodes: 1
    gpus_per_node: 1
  - nodes: 1
    gpus_per_node: 2
  - nodes: 1
    gpus_per_node: 4
  - nodes: 2
    gpus_per_node: 4
  - nodes: 4
    gpus_per_node: 4
