setup_file: /workspace/veros/veros/setups/global_flexible/global_flexible.py

launcher: srun
rank_env: SLURM_PROCID
local_rank_env: SLURM_LOCALID
memory_sample_interval: 5
profiler: nsys
profiler_args: "--trace=cuda,nvtx --sample=none --cuda-memory-usage=true --cuda-graph-trace=node"
timesteps: 100
repetitions: 1

container_image: $SINGULARITY_ALLOWED_DIR/veros.sif

environment:
  init: |
    module purge
    module load arch/h100

    export MPI4JAX_USE_CUDA_MPI=1
    export XLA_PYTHON_CLIENT_PREALLOCATE="false"
    export VEROS_ASSET_DIR=/lustre/fswork/projects/rech/yah/uyl42ho/veros_assets

strong:
  size: [720, 420, 80]

weak:
  local_size: [90, 40, 20]

topologies:
  - nodes: 1
    gpus_per_node: 1
  # - nodes: 1
  #   gpus_per_node: 2
  # - nodes: 1
  #   gpus_per_node: 4
  # - nodes: 2
  #   gpus_per_node: 4
  # - nodes: 3
  #   gpus_per_node: 4
  # - nodes: 4
  #   gpus_per_node: 4
